# Generated by Django 4.0.1 on 2022-08-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoruya nomi')),
                ('slug', models.SlugField(max_length=100, verbose_name='*')),
                ('img', models.ImageField(upload_to='category images/', verbose_name="Katego'riya rasmi")),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-id'],
            },
        ),
    ]
