# Generated by Django 4.0.1 on 2022-08-06 03:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name="Rang ko'di yoki nomi")),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Material nomi')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Hajm nomi')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tovar nomi')),
                ('slug', models.SlugField(max_length=150, verbose_name='*')),
                ('price', models.IntegerField(verbose_name='Narxi UZS')),
                ('priceDolor', models.FloatField(blank=True, verbose_name='Narxi USD')),
                ('about', ckeditor.fields.RichTextField()),
                ('imgFont', models.ImageField(upload_to='product images', verbose_name='Tovar rasmi oldi tomoni')),
                ('imgSide', models.ImageField(blank=True, upload_to='product images', verbose_name='Tovar rasmi yon tomoni hohishiy')),
                ('imgBack', models.ImageField(blank=True, upload_to='product images', verbose_name='Tovar rasmi orqa tomoni hohishiy')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='minoapp.category')),
                ('color', models.ManyToManyField(blank=True, related_name='product_color', to='minoapp.Color')),
                ('material', models.ManyToManyField(blank=True, related_name='product_material', to='minoapp.Material')),
                ('size', models.ManyToManyField(blank=True, related_name='product_size', to='minoapp.Size')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
