# Generated by Django 4.1 on 2022-08-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minoapp', '0002_color_material_size_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, to='minoapp.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(blank=True, to='minoapp.material'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='minoapp.size'),
        ),
    ]
